package metrics

import (
	"strconv"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	GatewayUp = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "netsepio_erebrus_gateway_up",
			Help: "Whether the Erebrus gateway is running. 1 means up.",
		},
		[]string{"environment", "version", "tag"},
	)

	BuildInfo = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "netsepio_erebrus_gateway_build_info",
			Help: "Build information for the Erebrus gateway. Value is always 1.",
		},
		[]string{"environment", "version", "tag"},
	)

	HTTPRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_requests_total",
			Help: "Total HTTP requests handled by Erebrus gateway.",
		},
		[]string{"method", "route", "status_code", "client", "environment"},
	)

	HTTPErrorsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_errors_total",
			Help: "Total HTTP error responses handled by Erebrus gateway.",
		},
		[]string{"method", "route", "status_code", "client", "environment"},
	)

	HTTPRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "netsepio_erebrus_gateway_request_duration_seconds",
			Help:    "HTTP request duration in seconds.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "route", "client", "environment"},
	)

	NodeRegistrationsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_node_registration_total",
			Help: "Total node registration attempts handled by gateway.",
		},
		[]string{"status", "environment"},
	)

	NodeHeartbeatsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_node_heartbeat_total",
			Help: "Total node heartbeats received by gateway.",
		},
		[]string{"status", "environment"},
	)

	VPNConfigsGeneratedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_vpn_config_generated_total",
			Help: "Total VPN configs generated by gateway.",
		},
		[]string{"client", "region", "status", "environment"},
	)

	AppEventsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "netsepio_erebrus_gateway_app_events_total",
			Help: "Safe app telemetry events received by gateway.",
		},
		[]string{"platform", "event", "status", "environment"},
	)

	ActiveNodeSessions = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "netsepio_erebrus_gateway_active_node_sessions",
			Help: "Current active node sessions known by gateway.",
		},
		[]string{"region", "environment"},
	)
)

func Register() {
	prometheus.MustRegister(
		GatewayUp,
		BuildInfo,
		HTTPRequestsTotal,
		HTTPErrorsTotal,
		HTTPRequestDuration,
		NodeRegistrationsTotal,
		NodeHeartbeatsTotal,
		VPNConfigsGeneratedTotal,
		AppEventsTotal,
		ActiveNodeSessions,
	)
}

func SetGatewayInfo(environment, version, tag string) {
	GatewayUp.WithLabelValues(environment, version, tag).Set(1)
	BuildInfo.WithLabelValues(environment, version, tag).Set(1)
}

func ObserveHTTPRequest(method, route string, statusCode int, client, environment string, started time.Time) {
	code := strconv.Itoa(statusCode)
	duration := time.Since(started).Seconds()

	HTTPRequestsTotal.WithLabelValues(method, route, code, client, environment).Inc()
	HTTPRequestDuration.WithLabelValues(method, route, client, environment).Observe(duration)

	if statusCode >= 400 {
		HTTPErrorsTotal.WithLabelValues(method, route, code, client, environment).Inc()
	}
}

func UpdateActiveNodeSessions(region string, count int, environment string) {
	region = NormalizeRegion(region)
	ActiveNodeSessions.WithLabelValues(region, environment).Set(float64(count))
}

func NormalizeRegion(region string) string {
	switch strings.ToLower(strings.TrimSpace(region)) {
	case "sg", "in", "eu", "us":
		return strings.ToLower(strings.TrimSpace(region))
	default:
		return "unknown"
	}
}

func NormalizePlatform(platform string) string {
	switch strings.ToLower(strings.TrimSpace(platform)) {
	case "android", "ios", "webapp":
		return strings.ToLower(strings.TrimSpace(platform))
	default:
		return "unknown"
	}
}

func NormalizeStatus(status string) string {
	switch strings.ToLower(strings.TrimSpace(status)) {
	case "success", "failed", "attempted":
		return strings.ToLower(strings.TrimSpace(status))
	default:
		return "unknown"
	}
}

func NormalizeEvent(event string) string {
	switch strings.ToLower(strings.TrimSpace(event)) {
	case
		"vpn_connect_attempt",
		"vpn_connect_success",
		"vpn_connect_failure",
		"vpn_disconnect",
		"region_selected",
		"node_selected",
		"drop_room_created",
		"file_transfer_success",
		"file_transfer_failure":
		return strings.ToLower(strings.TrimSpace(event))
	default:
		return "unknown"
	}
}